[project]
name = "task-tracker-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "google-generativeai>=0.8.5",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]
